name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install Trampoline
      run: |
        git clone https://github.com/TrampolineRTOS/trampoline.git
        cd trampoline
        git checkout -b trace origin/trace
        cd goil/makefile-unix/
        ./build+release.py
        sudo cp goil /usr/local/bin
        cd ../../viper
        make
        export VIPER_PATH=/opt/trampoline/viper
        echo 'export VIPER_PATH=/opt/trampoline/viper' >> ~/.bashrc
        cd
        sudo mv trampoline /opt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
